import type { Fish, Review, FishWithStats } from "./types";

/**
 * Mock data for local development.
 * TODO: Replace with Supabase queries once connected.
 */

export const MOCK_FISH: Fish[] = [
  {
    id: "1",
    name: "Wild Sardines in Extra Virgin Olive Oil",
    brand: "Wild Planet",
    fish_type: "sardine",
    weight_g: 124,
    calories: 210,
    protein_g: 17,
    fat_g: 15,
    sodium_mg: 250,
    salt_level: "salted",
    price_usd: 4.29,
    image_url: null,
    description: "Wild-caught sardines packed in high-quality EVOO. Sustainably sourced from the Pacific.",
    sourcing_notes: "Pacific Ocean, sustainably caught",
    created_at: "2026-01-15T00:00:00Z",
    updated_at: "2026-01-15T00:00:00Z",
  },
  {
    id: "2",
    name: "Smoked Trout Fillets",
    brand: "Scout",
    fish_type: "trout",
    weight_g: 100,
    calories: 180,
    protein_g: 20,
    fat_g: 11,
    sodium_mg: 320,
    salt_level: "salted",
    price_usd: 7.99,
    image_url: null,
    description: "PEI rainbow trout, smoked and hand-packed. Rich, buttery flavor.",
    sourcing_notes: "Prince Edward Island, Canada",
    created_at: "2026-02-01T00:00:00Z",
    updated_at: "2026-02-01T00:00:00Z",
  },
  {
    id: "3",
    name: "Tuna Fillets in Olive Oil",
    brand: "Ortiz",
    fish_type: "tuna",
    weight_g: 112,
    calories: 200,
    protein_g: 25,
    fat_g: 10,
    sodium_mg: 280,
    salt_level: "salted",
    price_usd: 9.49,
    image_url: null,
    description: "Yellowfin tuna, line-caught in the Cantabrian Sea. Premium quality, melt-in-your-mouth texture.",
    sourcing_notes: "Cantabrian Sea, Spain. Line-caught.",
    created_at: "2026-02-10T00:00:00Z",
    updated_at: "2026-02-10T00:00:00Z",
  },
  {
    id: "4",
    name: "Mackerel Fillets in Olive Oil",
    brand: "King Oscar",
    fish_type: "mackerel",
    weight_g: 115,
    calories: 190,
    protein_g: 18,
    fat_g: 13,
    sodium_mg: 300,
    salt_level: "salted",
    price_usd: 3.49,
    image_url: null,
    description: "Hand-selected Norwegian mackerel fillets. Bold, rich flavor with a firm texture.",
    sourcing_notes: "North Sea, Norway",
    created_at: "2026-03-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "5",
    name: "Smoked Sardines",
    brand: "Nuri",
    fish_type: "sardine",
    weight_g: 90,
    calories: 170,
    protein_g: 14,
    fat_g: 12,
    sodium_mg: 350,
    salt_level: "salted",
    price_usd: 6.99,
    image_url: null,
    description: "Portuguese sardines, lightly smoked and packed in olive oil. A classic from Matosinhos.",
    sourcing_notes: "Atlantic coast, Portugal",
    created_at: "2026-03-15T00:00:00Z",
    updated_at: "2026-03-15T00:00:00Z",
  },
  {
    id: "6",
    name: "Anchovies in Olive Oil",
    brand: "Ortiz",
    fish_type: "anchovy",
    weight_g: 47,
    calories: 90,
    protein_g: 13,
    fat_g: 4,
    sodium_mg: 1200,
    salt_level: "salted",
    price_usd: 8.99,
    image_url: null,
    description: "Salt-cured Cantabrian anchovies, hand-filleted and packed in olive oil. Intense umami.",
    sourcing_notes: "Bay of Biscay, Spain",
    created_at: "2026-04-01T00:00:00Z",
    updated_at: "2026-04-01T00:00:00Z",
  },
  {
    id: "7",
    name: "Sardines in Tomato Sauce",
    brand: "Trader Joe's",
    fish_type: "sardine",
    weight_g: 120,
    calories: 160,
    protein_g: 15,
    fat_g: 8,
    sodium_mg: 400,
    salt_level: "salted",
    price_usd: 2.49,
    image_url: null,
    description: "Budget-friendly sardines in a simple tomato sauce. Good protein per dollar.",
    sourcing_notes: "Morocco",
    created_at: "2026-04-10T00:00:00Z",
    updated_at: "2026-04-10T00:00:00Z",
  },
  {
    id: "8",
    name: "Smoked Mussels",
    brand: "Patagonia Provisions",
    fish_type: "mussel",
    weight_g: 120,
    calories: 160,
    protein_g: 16,
    fat_g: 7,
    sodium_mg: 280,
    salt_level: "salted",
    price_usd: 8.49,
    image_url: null,
    description: "Savory smoked mussels from Galicia, Spain. Plump, tender, with a deep smoky flavor.",
    sourcing_notes: "Galicia, Spain. Rope-grown.",
    created_at: "2026-05-01T00:00:00Z",
    updated_at: "2026-05-01T00:00:00Z",
  },
];

export const MOCK_REVIEWS: (Review & { user_name: string })[] = [
  {
    id: "r1",
    user_id: "u1",
    fish_id: "1",
    flavor_score: 7,
    texture_score: 7,
    aesthetics_score: 6,
    value_score: 9,
    overall_score: 8,
    notes: "Great everyday sardine. Olive oil is quality. Bones are soft and unnoticeable. Best value in the category.",
    is_from_tasting: true,
    tasting_id: "t1",
    created_at: "2026-05-10T00:00:00Z",
    updated_at: "2026-05-10T00:00:00Z",
    user_name: "FishFan42",
  },
  {
    id: "r2",
    user_id: "u2",
    fish_id: "1",
    flavor_score: 8,
    texture_score: 6,
    aesthetics_score: 5,
    value_score: 9,
    overall_score: 7,
    notes: "Solid sardine. Not the prettiest tin but the taste and price point are hard to beat.",
    is_from_tasting: false,
    tasting_id: null,
    created_at: "2026-05-12T00:00:00Z",
    updated_at: "2026-05-12T00:00:00Z",
    user_name: "TinOpener",
  },
  {
    id: "r3",
    user_id: "u1",
    fish_id: "3",
    flavor_score: 9,
    texture_score: 10,
    aesthetics_score: 9,
    value_score: 6,
    overall_score: 9,
    notes: "Incredible texture — literally melts. The premium price is justified. This is what tinned tuna should be.",
    is_from_tasting: true,
    tasting_id: "t1",
    created_at: "2026-05-10T00:00:00Z",
    updated_at: "2026-05-10T00:00:00Z",
    user_name: "FishFan42",
  },
  {
    id: "r4",
    user_id: "u3",
    fish_id: "3",
    flavor_score: 9,
    texture_score: 9,
    aesthetics_score: 8,
    value_score: 5,
    overall_score: 8,
    notes: "The gold standard of tinned tuna. Expensive but you can taste the difference immediately.",
    is_from_tasting: false,
    tasting_id: null,
    created_at: "2026-05-15T00:00:00Z",
    updated_at: "2026-05-15T00:00:00Z",
    user_name: "SardineQueen",
  },
  {
    id: "r5",
    user_id: "u2",
    fish_id: "4",
    flavor_score: 7,
    texture_score: 8,
    aesthetics_score: 7,
    value_score: 10,
    overall_score: 8,
    notes: "Unbeatable value. Rich mackerel flavor, firm texture, great on toast. My go-to weeknight protein.",
    is_from_tasting: true,
    tasting_id: "t1",
    created_at: "2026-05-10T00:00:00Z",
    updated_at: "2026-05-10T00:00:00Z",
    user_name: "TinOpener",
  },
  {
    id: "r6",
    user_id: "u3",
    fish_id: "5",
    flavor_score: 9,
    texture_score: 8,
    aesthetics_score: 9,
    value_score: 7,
    overall_score: 9,
    notes: "Beautiful tin, beautiful fish. The smoke is delicate, not overpowering. A special occasion sardine.",
    is_from_tasting: false,
    tasting_id: null,
    created_at: "2026-05-20T00:00:00Z",
    updated_at: "2026-05-20T00:00:00Z",
    user_name: "SardineQueen",
  },
  {
    id: "r7",
    user_id: "u1",
    fish_id: "6",
    flavor_score: 10,
    texture_score: 9,
    aesthetics_score: 8,
    value_score: 5,
    overall_score: 9,
    notes: "Pure umami bomb. The best anchovies I've ever had. Worth every penny if you love anchovies.",
    is_from_tasting: true,
    tasting_id: "t1",
    created_at: "2026-05-10T00:00:00Z",
    updated_at: "2026-05-10T00:00:00Z",
    user_name: "FishFan42",
  },
  {
    id: "r8",
    user_id: "u2",
    fish_id: "7",
    flavor_score: 5,
    texture_score: 5,
    aesthetics_score: 4,
    value_score: 9,
    overall_score: 6,
    notes: "Fine for the price. Nothing special but you can't argue with $2.49 for decent protein.",
    is_from_tasting: false,
    tasting_id: null,
    created_at: "2026-05-22T00:00:00Z",
    updated_at: "2026-05-22T00:00:00Z",
    user_name: "TinOpener",
  },
  {
    id: "r9",
    user_id: "u3",
    fish_id: "2",
    flavor_score: 8,
    texture_score: 9,
    aesthetics_score: 8,
    value_score: 6,
    overall_score: 8,
    notes: "Buttery and rich. Beautiful presentation. Slightly pricey but the quality shows.",
    is_from_tasting: true,
    tasting_id: "t1",
    created_at: "2026-05-10T00:00:00Z",
    updated_at: "2026-05-10T00:00:00Z",
    user_name: "SardineQueen",
  },
  {
    id: "r10",
    user_id: "u1",
    fish_id: "8",
    flavor_score: 8,
    texture_score: 7,
    aesthetics_score: 8,
    value_score: 6,
    overall_score: 8,
    notes: "Smoky, plump mussels. Great as a snack or on crackers. The brand's sustainability story is a plus.",
    is_from_tasting: false,
    tasting_id: null,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    user_name: "FishFan42",
  },
];

/** Compute stats for each fish from the mock reviews */
export function getMockFishWithStats(): FishWithStats[] {
  return MOCK_FISH.map((fish) => {
    const fishReviews = MOCK_REVIEWS.filter((r) => r.fish_id === fish.id);
    const count = fishReviews.length;

    if (count === 0) {
      return {
        ...fish,
        avg_overall: null,
        avg_flavor: null,
        avg_texture: null,
        avg_aesthetics: null,
        avg_value: null,
        review_count: 0,
        tasting_review_count: 0,
      };
    }

    const avg = (scores: number[]) =>
      Math.round((scores.reduce((a, b) => a + b, 0) / scores.length) * 10) / 10;
    const avgNullable = (scores: (number | null)[]) => {
      const present = scores.filter((s): s is number => s != null);
      return present.length > 0 ? avg(present) : null;
    };

    return {
      ...fish,
      avg_overall: avg(fishReviews.map((r) => r.overall_score)),
      avg_flavor: avg(fishReviews.map((r) => r.flavor_score)),
      avg_texture: avg(fishReviews.map((r) => r.texture_score)),
      avg_aesthetics: avg(fishReviews.map((r) => r.aesthetics_score)),
      avg_value: avgNullable(fishReviews.map((r) => r.value_score)),
      review_count: count,
      tasting_review_count: fishReviews.filter((r) => r.is_from_tasting).length,
    };
  });
}

export function getMockFishById(id: string): Fish | undefined {
  return MOCK_FISH.find((f) => f.id === id);
}

export function getMockReviewsForFish(fishId: string) {
  return MOCK_REVIEWS.filter((r) => r.fish_id === fishId);
}
