INSERT INTO fish (name, brand, fish_type, weight_g, calories, protein_g, price_usd, description) VALUES
-- Mackerel
('Mackerel Fillets with Curry and Chilli, in EV Olive Oil', 'The Rebel of the Sea', 'mackerel', 90, 330, 18, 10.99, 'Mackerel fillets with curry and chilli, in extra virgin olive oil, salt'),
('Wild Mackerel, in EV Olive Oil', 'Matiz', 'mackerel', 85, 160, 19, 6.59, 'Wild mackerel in extra virgin olive oil, salt'),
('Wild Mackerel, in EV Olive Oil', 'Cole''s', 'mackerel', 85, 170, 20, 5.99, 'Wild mackerel in extra virgin olive oil, salt'),
('Mackerel, in EV Olive Oil', 'La Narval', 'mackerel', 84, 190, 21, 5.49, 'Mackerel in extra virgin olive oil, salt'),
('Mackerel Fillets, in Spicy EV Olive Oil', 'Minerva', 'mackerel', 85, 160, 21, 5.49, 'Mackerel fillets in spicy extra virgin olive oil, salt'),
('Mackerel Fillets with Curry and Chilli, in EV Olive Oil', 'Miss Can', 'mackerel', 120, 450, 24, 11.99, 'Mackerel fillets with curry and chilli, in extra virgin olive oil, salt'),
('Spiced Mackerel Fillets, in EV Olive Oil', 'Pinhais "Nuri"', 'mackerel', 125, 297, 30, 10.95, 'Spiced mackerel fillets in extra virgin olive oil, salt'),
-- Salmon
('Smoked Salmon, in EV Olive Oil', 'Fish Wife', 'salmon', 67, 180, 19, 11.99, 'Smoked salmon in extra virgin olive oil, salt'),
('Smoked Salmon with Sichuan Chili Crisp', 'Fish Wife', 'salmon', 90, 340, 19, 14.99, 'Smoked salmon with Sichuan chili crisp'),
('Wild Smoked Pink Salmon with Pastrami Spice', 'Patagonia Provisions', 'salmon', 85, 140, 20, 9.99, 'Wild smoked pink salmon with pastrami spice'),
('Wild Smoked Pink Salmon with Brown Sugar', 'Patagonia Provisions', 'salmon', 85, 130, 20, 9.99, 'Wild smoked pink salmon with brown sugar'),
('Lightly Smoked Salmon, in EV Olive Oil', 'Trader Joes', 'salmon', 100, 190, 21, 3.99, 'Lightly smoked salmon in extra virgin olive oil, salt'),
-- Sardines
('Sardines, in EV Olive Oil', 'Millesimate', 'sardine', 100, 200, 10, 9.79, 'Sardines in extra virgin olive oil'),
('Grilled Sardines, in EV Olive Oil', 'Trader Joes', 'sardine', 77, 390, 15, 3.99, 'Grilled sardines in extra virgin olive oil'),
('Sardines with Preserved Lemon, in EV Olive Oil', 'Fish Wife', 'sardine', 84, 200, 18, 8.79, 'Sardines with preserved lemon, in extra virgin olive oil'),
('Small Sardines, in Truffle Oil', 'La Curiosa', 'sardine', 77, 170, 20, 13.99, 'Small sardines in truffle oil'),
('Lightly Smoked Sardines, in EV Olive Oil', 'Matiz', 'sardine', 84, 175, 20, 5.49, 'Lightly smoked sardines in extra virgin olive oil'),
('Wild Sardines with Smoke Flavor, in EV Olive Oil', 'Trader Joes', 'sardine', 85, 180, 21, 2.29, 'Wild sardines with smoke flavor, in extra virgin olive oil'),
('Sardine Fillets, in EV Olive Oil', 'Season', 'sardine', 85, 200, 22, 2.83, 'Sardine fillets in extra virgin olive oil'),
('Sardines with Lemon, in EV Olive Oil', 'Pinhais "Nuri"', 'sardine', 125, 320, 25, 7.69, 'Sardines with lemon, in extra virgin olive oil'),
('Sardines, in EV Olive Oil', 'Miss Can', 'sardine', 120, 390, 30, 14.00, 'Sardines in extra virgin olive oil'),
-- Trout
('Rainbow Trout with Dill, in Sunflower Oil', 'Scout', 'trout', 90, 240, 16, 7.99, 'Rainbow trout with dill, in sunflower oil'),
('Farm Raised Smoked Trout Fillets, in Canola Oil', 'Trader Joes', 'trout', 77, 140, 20, 4.79, 'Farm raised smoked trout fillets, in canola oil, salt'),
('Smoked Trout with Red Chimichurri', 'Fish Wife', 'trout', 105, 190, 22, 12.99, 'Smoked trout with red chimichurri'),
-- Tuna
('Albacore Tuna with Soy Ginger, in Mirin', 'Fish Wife', 'tuna', 92, 120, 16, 7.99, 'Albacore tuna with soy ginger, in mirin'),
('Albacore Tuna, in Spicy EV Olive Oil', 'Fish Wife', 'tuna', 67, 190, 17, 7.99, 'Albacore tuna in spicy extra virgin olive oil'),
('Albacore Tuna, in EV Olive Oil', 'Fish Wife', 'tuna', 67, 190, 17, 7.99, 'Albacore tuna in extra virgin olive oil'),
('Albacore Tuna with Spanish Lemon, in EV Olive Oil', 'Fish Wife', 'tuna', 67, 190, 17, 7.99, 'Albacore tuna with Spanish lemon, in extra virgin olive oil'),
('Yellowfin Tuna Belly Fillets, in EV Olive Oil', 'La Narval', 'tuna', 73, 150, 17, 9.99, 'Yellowfin tuna belly fillets in extra virgin olive oil, salt'),
('White Tuna, in EV Olive Oil', 'Ortiz', 'tuna', 82, 260, 17, 8.99, 'White tuna in extra virgin olive oil, salt'),
('Yellowfin Tuna Filets, in EV Olive Oil', 'Natural Catch', 'tuna', 85, 130, 21, 5.79, 'Yellowfin tuna filets in extra virgin olive oil, salt'),
('Spicy Yellowfin Tuna Filets, in EV Olive Oil', 'Natural Catch', 'tuna', 85, 130, 21, 5.79, 'Spicy yellowfin tuna filets in extra virgin olive oil, salt'),
('Chunk Light Skipjack Tuna, in Water', 'Trader Joes', 'tuna', 113, 110, 25, 1.79, 'Chunk light skipjack tuna in water, salt'),
('Solid Light Yellowfin Tuna, in EV Olive Oil', 'Trader Joes', 'tuna', 113, 260, 26, 2.49, 'Solid light yellowfin tuna in extra virgin olive oil, salt'),
('Solid White Albacore Tuna, in Water, No Salt', 'Trader Joes', 'tuna', 113, 130, 29, 1.99, 'Solid white albacore tuna in water, no salt added'),
('Solid White Albacore Tuna, in Water, Low Sodium', 'Trader Joes', 'tuna', 113, 130, 29, 1.99, 'Solid white albacore tuna in water, low sodium'),
('Solid White Albacore Tuna, in Water', 'Trader Joes', 'tuna', 113, 130, 29, 1.99, 'Solid white albacore tuna in water, salt'),
('Solid White Albacore Tuna, in EV Olive Oil', 'Trader Joes', 'tuna', 113, 220, 29, 2.49, 'Solid white albacore tuna in extra virgin olive oil, salt'),
('Wild Albacore Tuna Fillets, in Water, No Salt', 'American Tuna', 'tuna', 142, 240, 36, 8.99, 'Wild albacore tuna fillets in water, no salt added'),
('Wild Albacore Tuna Fillets, in Water', 'American Tuna', 'tuna', 142, 240, 36, 8.99, 'Wild albacore tuna fillets in water, salt'),
('Solid White Albacore Tuna, in EV Olive Oil', 'St. Jude Tuna', 'tuna', 170, 480, 42, 9.99, 'Solid white albacore tuna in extra virgin olive oil, salt'),
('White Tuna Jar, in EV Olive Oil', 'Ortiz', 'tuna', 150, 320, 44, 20.99, 'White tuna jar in extra virgin olive oil, salt'),
('Albacore Tuna, in Water', 'Lummi Island Wild', 'tuna', 170, 240, 48, 9.99, 'Albacore tuna in water, salt'),
('Albacore Tuna, in Water', 'Island Trollers', 'tuna', 212, 412, 60, 10.49, 'Albacore tuna in water, salt'),
('Jalapeno Albacore Tuna, in Water', 'Island Trollers', 'tuna', 212, 412, 60, 10.49, 'Jalapeno albacore tuna in water, salt');
